# Generated by Django 3.1.7 on 2021-03-27 06:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='creation time'),
        ),
    ]
